// This script is generated by AI, but has been modified.
#if false
using Godot;
using System;
using System.Collections.Generic;
using static Godot.Control;
using static System.Net.Mime.MediaTypeNames;


[Tool]
public partial class QuestionEditorWindow : Window
{
    protected QuestionData _current_question;

    protected Sprite2D _question_sprite;
    protected Sprite2D _on_question_answer_sprite;
    protected Node2D _answers_container;

    protected OptionButton _question_selector_btn;
    protected Button _load_question;
    protected Button _save_question;
    protected CheckBox _show_grid_check;
    protected SpinBox _zoom_spin;
    protected GridDrawer _grid_drawer;

    protected SubViewportContainer _viewport_container;
    protected SubViewport _viewport;
    protected Node2D _preview_scene;
    protected Camera2D _camera;

    protected EditorInterface _editor_interface;
    protected bool _is_dragging = false;
    protected string _drag_target = "";
    protected Vector2 _drag_offset;


    public QuestionEditorWindow()
    {
        Title = "Question Data Editor";
        Size = new Vector2I(1200, 800);
        Borderless = false;
        Unresizable = false;
    }

    public void Initialize(EditorInterface editor_interface)
    {
        _editor_interface = editor_interface;
    }

    public override void _Ready()
    {
        _SetupUI();
        _SetupViewport();
    }

    public void LoadQuestion(QuestionData question)
    {
        _current_question = question;
        UpdatePreview();
    }

    /// <summary>
    /// Setup the UI layout. <br />
    /// 
    /// 1. Left panel for tools. <br />
    /// 2. Right panel for previewing.
    /// </summary>
    protected void _SetupUI()
    {
        var main_hbox = new HBoxContainer();
        AddChild(main_hbox);
        main_hbox.SetAnchorsPreset(LayoutPreset.FullRect);

        // 左侧工具栏
        var left_panel = new VBoxContainer();
        left_panel.CustomMinimumSize = new Vector2(250, 0);
        main_hbox.AddChild(left_panel);

        _SetupToolbar(left_panel);

        // 右侧预览区域
        var right_panel = new VBoxContainer();
        main_hbox.AddChild(right_panel);
        right_panel.SizeFlagsHorizontal = SizeFlags.ExpandFill;

        _SetupPreview(right_panel);
    }


    /// <summary>
    /// 
    /// </summary>
    protected void _SetupViewport()
    {
        _viewport = new SubViewport
        {
            TransparentBg = false,
            Size = new Vector2I(1920, 1080),
            HandleInputLocally = false
        };
        _viewport_container.AddChild(_viewport);

        _preview_scene = new Node2D();
        _viewport.AddChild(_preview_scene);

        _camera = new Camera2D
        {
            Position = new Vector2(960, 540),
            Enabled = true
        };
        _preview_scene.AddChild(_camera);

        // 背景
        var background = new ColorRect
        {
            Color = new Color(0.15f, 0.15f, 0.15f),
            Size = new Vector2(1920, 1080)
        };
        _preview_scene.AddChild(background);

        // 网格绘制器
        _grid_drawer = new GridDrawer();
        _preview_scene.AddChild(_grid_drawer);

        _question_sprite = new Sprite2D();
        _preview_scene.AddChild(_question_sprite);

        _on_question_answer_sprite = new Sprite2D();
        _preview_scene.AddChild(_on_question_answer_sprite);

        _answers_container = new Node2D();
        _preview_scene.AddChild(_answers_container);
    }


    protected void _SetupToolbar(VBoxContainer left_panel)
    {

        var title = new Label();
        title.Text = "Question Editor";
        title.HorizontalAlignment = HorizontalAlignment.Center;
        title.AddThemeColorOverride("font_color", new Color(0.3f, 0.7f, 1.0f));
        title.AddThemeFontSizeOverride("font_size", 18);
        left_panel.AddChild(title);

        left_panel.AddChild(new HSeparator());

        // 题目选择器
        var selector_label = new Label();
        selector_label.Text = "Select a question to edit: ";
        left_panel.AddChild(selector_label);

        _question_selector_btn = new OptionButton();
        _question_selector_btn.ItemSelected += _OnQuestionSelected;
        left_panel.AddChild(_question_selector_btn);

        _load_question = new Button();
        _load_question.Text = "Load from file";
        _load_question.Pressed += _OnLoadFromFile;
        left_panel.AddChild(_load_question);

        left_panel.AddChild(new HSeparator());

        // 视图控制
        var view_settings_label = new Label();
        view_settings_label.Text = "View settings";
        left_panel.AddChild(view_settings_label);

        _show_grid_check = new CheckBox();
        _show_grid_check.Text = "Show grid";
        _show_grid_check.ButtonPressed = true;
        _show_grid_check.Toggled += (pressed) =>
        {
            if (_grid_drawer != null) _grid_drawer.Visible = pressed;
        };
        left_panel.AddChild(_show_grid_check);

        var zoom_container = new HBoxContainer();
        left_panel.AddChild(zoom_container);
        var zoom_label = new Label();
        zoom_label.Text = "Zoom";
        zoom_container.AddChild(zoom_label);
        _zoom_spin = new SpinBox
        {
            MinValue = 0.5,
            MaxValue = 3.0,
            Step = 0.1,
            Value = 1.0
        };
        _zoom_spin.ValueChanged += _OnZoomChanged;
        zoom_container.AddChild(_zoom_spin);

        left_panel.AddChild(new HSeparator());

        // 操作说明
        var help_label = new RichTextLabel();
        help_label.BbcodeEnabled = true;
        help_label.FitContent = true;
        help_label.CustomMinimumSize = new Vector2(0, 200);
        help_label.Text = @"[b]操作说明:[/b]

• 拖拽题目图片调整位置
• 拖拽选项按钮调整位置
• 拖拽答案区域调整位置
• Ctrl+S 保存
• 鼠标滚轮缩放

[color=yellow]位置信息会实时保存到Resource[/color]";
        left_panel.AddChild(help_label);
        left_panel.AddChild(new HSeparator());

        _save_question = new Button();
        _save_question.Text = "Save question to file";
        _save_question.Pressed += _OnSaveQuestion;
        left_panel.AddChild(_save_question);
    }


    protected void _SetupPreview(VBoxContainer right_panel)
    {
        var toolbar = new HBoxContainer();
        right_panel.AddChild(toolbar);

        var info_label = new Label
        {
            Text = "💡 拖拽元素调整位置，修改会实时保存到Resource",
            HorizontalAlignment = HorizontalAlignment.Center
        };
        info_label.AddThemeColorOverride("font_color", new Color(1.0f, 0.8f, 0.3f));
        toolbar.AddChild(info_label);
        toolbar.SizeFlagsHorizontal = SizeFlags.ExpandFill;

        _viewport_container = new SubViewportContainer
        {
            Stretch = true,
            FocusMode = FocusModeEnum.All
        };
        right_panel.AddChild(_viewport_container);
        _viewport_container.SizeFlagsVertical = SizeFlags.ExpandFill;
        _viewport_container.GuiInput += _OnViewportGuiInput;
    }


    protected void _OnQuestionSelected(long index)
    {
        // TODO: Select Question.
    }


    protected void _OnLoadFromFile()
    {
        // TODO: Load from file.
    }


    public void UpdatePreview()
    {
        if (_current_question == null) return;

        if (_current_question.QuestionImage != null)
        {
            _question_sprite.Texture = _current_question.QuestionImage;
            _question_sprite.Position = _current_question.QuestionPosition;
            _question_sprite.Visible = true;
        }

        List<Texture2D> _answers = new List<Texture2D>();
        _answers.Add(_current_question.CorrectAnswer);
        // 答案预览
        if (_current_question.WrongAnswerOptions != null && _current_question.WrongAnswerOptions.Length > 0)
        {
            _answers.AddRange(_current_question.WrongAnswerOptions);
        }
        _on_question_answer_sprite.Texture = _current_question.CorrectAnswer;
        _on_question_answer_sprite.Position = _current_question.OnQuestionAnswerPosition;
        _on_question_answer_sprite.Scale = new Vector2(_current_question.OnQuestionAnswerScale, _current_question.OnQuestionAnswerScale);
        _on_question_answer_sprite.Modulate = new Color(1, 1, 1, 0.6f);
        _on_question_answer_sprite.Visible = true;

        // 选项
        _UpdateOptions(_answers);

        _viewport.RenderTargetUpdateMode = SubViewport.UpdateMode.Always;
    }


    protected void _UpdateOptions(List<Texture2D> answers)
    {
        foreach (var child in _answers_container.GetChildren())
        {
            child.QueueFree();
        }


        for (int i = 0; i < answers.Count; i++)
        {
            var sprite = new Sprite2D
            {
                Texture = answers[i],
                Position = _currentQuestion.AnswerOptionPositions[i],
                Modulate = new Color(1, 1, 0.5f, 0.8f),
                Name = $"Option_{i}"
            };
            _optionsContainer.AddChild(sprite);
        }
    }

    
    protected void _OnZoomChanged(double value)
    {

    }

    protected void _OnSaveQuestion()
    {

    }

    protected void _OnViewportGuiInput(InputEvent inputEvent)
    {

    }
}

[Tool]
public partial class GridDrawer: Node2D
{
    private int _gridSize = 50;
    private Color _gridColor = new Color(0.3f, 0.3f, 0.3f, 0.5f);
    private Color _majorGridColor = new Color(0.4f, 0.4f, 0.4f, 0.8f);

    public override void _Draw()
    {
        var viewportSize = new Vector2(1920, 1080);

        // 绘制小网格线（每50像素）
        for (float x = 0; x <= viewportSize.X; x += _gridSize)
        {
            DrawLine(new Vector2(x, 0), new Vector2(x, viewportSize.Y), _gridColor, 1);
        }

        for (float y = 0; y <= viewportSize.Y; y += _gridSize)
        {
            DrawLine(new Vector2(0, y), new Vector2(viewportSize.X, y), _gridColor, 1);
        }

        // 绘制主网格线（每200像素）
        for (float x = 0; x <= viewportSize.X; x += _gridSize * 4)
        {
            DrawLine(new Vector2(x, 0), new Vector2(x, viewportSize.Y), _majorGridColor, 2);
        }

        for (float y = 0; y <= viewportSize.Y; y += _gridSize * 4)
        {
            DrawLine(new Vector2(0, y), new Vector2(viewportSize.X, y), _majorGridColor, 2);
        }
    }
}

#endif
