<Project Sdk="Godot.NET.Sdk/4.5.1">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <RootNamespace>SaveMyGPA</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <Folder Include="scenes\prefabs\classrooms\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="ZLinq" Version="1.5.4" />
    <PackageReference Include="ZLinq.Godot" Version="1.5.4" />
  </ItemGroup>
</Project>